# Generated by Django 5.0 on 2024-05-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=100)),
                ('university_image', models.TextField()),
                ('university_overview', models.TextField()),
                ('university_fields', models.CharField(max_length=100)),
                ('university_location', models.CharField(max_length=100)),
                ('university_ranking', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('website', models.URLField()),
            ],
        ),
    ]
